### ISSUE TITLE
Set tasks as recurring at certain intervals

### ISSUE THREAD

**Issue by loveandbejoyful** [CS2103JAN2017-T09-B4/main#37]
So that I can save time having to add the task repeatedly for different times

**Comment by BrandonTJS** [comment]
Placeholders are in place

**Comment by loveandbejoyful** [comment]
Might need to make some changes to Logic component design

**Comment by loveandbejoyful** [comment]
For the same recurring task, show:
- overdue instances (and the earliest one coming up) separately
- 1 general task which states the recurring interval (e.g. every Friday)
(can complete them respectively using their indices)

**Comment by BrandonTJS** [comment]
Implemented
