### ISSUE TITLE
Set notifications to go off before the start date / time of a task

### ISSUE THREAD

**Issue by loveandbejoyful** [CS2103JAN2017-T09-B4/main#42]
So that I can remind myself to work on those tasks that need to be completed

**Comment by BrandonTJS** [comment]
Need clarification, how is this different from #41? @loveandbejoyful

**Comment by Crsytral** [comment]
@loveandbejoyful whats the duration before the start time to notify? one/two hr before start_date?

**Comment by loveandbejoyful** [comment]
@Crsytral 2 hrs seems pretty safe
